#+startup: beamer
#+TITLE: Lambda Calculi and You
#+AUTHOR: Clarissa Littler
#+OPTIONS: H:2 toc:nil
#+latex_header: \usetheme{Hannover}
#+latex_header: \usecolortheme{rose}
#+LaTeX_HEADER: \usepackage{minted}
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [bigger]

* Ideas                                                            :noexport:
  So this talk is going to fulfill the dual roles of 
  + introducing the lambda calculus
  + showing lessons and ideas you can take away from the untyped lambda calculus

  What are the takeaways from the untyped lambda calculus
  + first class functions are a common language between many programming languages, allowing you to bootstrap your way into unfamiliar syntax
  + closures are /incredibly/ powerful
    + use closures whenever you can!
    + frameworks like React have been learning this by emphasizing functional components over object constructors
    + closures can be used to make objects and classes
  + think of data in terms of how it's used
    + data has an inherent computational content, which is the lesson of Church encodings
    + think of data in terms of how it should be used, not just what should be stored
    + you can derive what your functions for using data should look like by thinking of the Church encoding
** Vague outline
*** Intro
    + The lambda calculus
    + The goals of this talk
      + introduce you to lambda calculi
      + data is defined by how its used
      + closures are more powerful than you might think
      + desugaring isn't just for React
      + if you can find the lambda calculus in a language, you can code in it
    + Lambda calculus
      + History - Alonzo Church answering questions of computability and proof theory
      + Syntax - only three forms variables, applications, function abstraction
      + The computation - in substitution and substitution only
    + Where's the data?
      + Church encodings
      + Booleans
	+ True
	+ False
	+ If statements
      + Natural numbers
	+ 0 and suc
	+ small numerals
	+ natural numbers as for-loops
	+ all operations are functions
      + Lists
	+ head and tail
	+ list as fold
      + Trees
	+ left and right
	+ trees are traversals
    + Adding control
      + Y-combinators
    + The power of closures
      + Stateful variables
      + Can fake in the lambda calculus
	+ That's what monads were /actually/ for
      + Let statements
      + Lambda + stateful variables = closures
      + Closures are
	+ Objects
	+ Classes
	+ Modules
	+ All through the power of functions
	+ More common knowledge thanks to JavaScript
    + Learning new languages
      + If you can find the lambda calculus in a language, you can do almost anything
      + If you can /translate/ to the lambda calculus, you understand everything
*** Script
    We're aiming for about 4-6000 words in order for it to be properly timed
**** Draft 1
     Hi everyone! 

     Welcome to this talk I'm glad to be speaking at Open Source Bridge again. This year I'll be giving a talk we're calling "Learn the lambda calculus and be a better programmer". It's a bold title to be sure, but I'm hoping we'll be able to back up that claim. 

     So we're going to cover a few things today. First, what exactly /is/ the lambda calculus? Then the bulk of our talk we'll be covering how one /programs/ in it. Then finally we'll be applying these ideas to the larger programming world and exploring how understanding lambda calculi in general will help you bridge common ground between all the languages you ever need to learn.

     Obviously, the first question is what I even mean by "lambda calculus". Actually, it's more appropriate to same lambda /calculi/ because it's actually an entire family of formal pen-and-paper systems of computation. We'll be starting with the most basic one: the /untyped lambda calculus/.

     The untyped lambda calculus was an invention of Alonzo Church, Alan Turing's thesis advisor (double check), who was also working on the same problems on the limits of computation that caused his student to invent the Turing machine. While Turing machines model computation in a very mechanical, physical, way Church's lambda calculus was a pen & paper equational thing that is closer to an actual programming language.

     I mean, it's not /that/ close to a programming language as you might be used to. This is an example of how the lambda calculus would encode the factorial function! (picture)

     To me, this looks like a math class more than a programming class! That's not a coincidence as Church was a mathematician writing for other mathematicians about what can be theoretically calculated by an algorithm. I doubt he had anything like a modern computer in mind, given than at the time "computer" was still a job title you gave to people who worked through complex calculations for a living.

     How does the untyped lambda calculus work? It's has a /very/ simple syntax: only three forms. Those are (1) lambda abstraction, which is how you /create/ functions, (2) application, which is how you use functions, and variables.

     If you're not used to variables in a /functional/ language I want to clarify that these variables can't actually change value over the course of the program. They're like the parameters of a function in a call-by-value language not like the mutable variables of a Python, C-family language, etc. 

     We should also point out that for now there's no such thing as multi-argument functions. In the untyped lambda calculus, a 

     So here's about the simplest possible function you can create in the lambda calculus: the /identity/ function. It has the incredibly important role of being a function that does nothing at all to its argument.
     (\x. x)
     We write function applications just by adjacency so to apply the identity function to a term /a/ you'd write (\x. x) a.

     The final thing we need to explain is how to evaluate code. There's only one thing that can happen in a lambda calculus program: functional evaluation. To evaluate a function application or function call you /substitute/ in the value forthe variable everywhere. This really isn't very different than how function applications work in any programming language
     If you had a chunk of Python code like this
 #+BEGIN_SRC python :exports code :results output
   def funk(f,a,b):
       print(f(a))
       print(f(b))

   def dub(x):
       return (x + x)
    
   funk(dub,2,4)
 #+END_SRC

 #+RESULTS:
 : 4
 : 8

   How does the function call to =funk= look after substituting in the arguments? Well it becomes something kinda like

 #+BEGIN_SRC python :exports code :results output
   def funk(f,a,b):
       print(f(a))
       print(f(b))

   def dub(x):
       return (x + x)
    
   print(dub(2))
   print(dub(4))
 #+END_SRC

That's not /exactly/ a perfect analogy but you can get the rough picture of how it works at least. The important thing is that substitution at the end of the day is pretty straightforward.

I say /pretty/ straightforward because the actual details of defining substitution in the lambda calculus, which is specifically called "capture-avoiding substitution", is the plugging-in-a-USB-cord of programming language design. No one ever does it right on the first try. You'll mess up. Mess up again. Then try to go back to your first mistake and probably fix it. All that being said, we're going to avoid the details of substition in this talk. The overall concepts are simple, but Legion is waiting in the details. 

So we've already said (EDIT: no we didn't) that the untyped lambda calculus  

* Introduction
** What you'll learn
   What the $\lambda$ calculus is, how to calculate with it, and lessons to draw from it 
** History of $\lambda$ calculus
***                                                               :B_columns:
    :PROPERTIES:
    :BEAMER_env: columns
    :END:
****                                                                  :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.45
     :END:
file:~/Pictures/Church.jpeg
****                                                                  :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.45
     :END:
#+BEGIN_EXPORT latex
$\textasciicircum{} \rightarrow \Lambda \rightarrow \lambda$
#+END_EXPORT
* Syntax and calculation
** What is it?
  + $\lambda x. M$
  + $M N$
  + $x$
** Let's break it down
#+BEGIN_EXPORT latex
$\lambda x. M$
#+END_EXPORT

#+BEGIN_EXAMPLE
function (x) {
  M
}

(lambda x: M)

{ |x| M}
#+END_EXAMPLE
** Sample programs
#+BEGIN_EXPORT latex
\begin{align*}
  \text{id} &= \lambda x. x \\
  \text{double} &= \lambda f. \lambda x. f (f\,x) \\
  \text{if} &= \lambda b. \lambda t. \lambda f. b\,t\,f \\
\end{align*}
#+END_EXPORT
** Substitution: where computation happens
#+BEGIN_EXPORT latex
$(\lambda x. M) N \rightarrow N[M/x]$
#+END_EXPORT
** You've seen this
#+BEGIN_SRC python :exports code
  def sillyFun(x):
      y = x + 2
      print(y)
      return (x*x)
#+END_SRC

** You've seen this
#+BEGIN_SRC python :exports code
  sillyFun(3):
    y = 3 + 2
    print(y)
    return (3 * 3)
#+END_SRC
** Evaluation order
*** Functions before arguments
#+BEGIN_EXPORT latex
$M N \rightarrow (\lambda x. l) N$
#+END_EXPORT
** Capture avoidance
*** 
#+BEGIN_EXPORT latex
$(\lambda x. \lambda y. x\, y) y \rightarrow \lambda y. y\, y$ 
#+END_EXPORT

But /that/ can't be right!
** Rename variables
*** 
#+BEGIN_EXPORT latex
$(\lambda x. \lambda z. x\, z) y \rightarrow \lambda z. y\, z$ 
#+END_EXPORT
** Can't get it right
#+ATTR_LATEX: :width 5cm
file:~/Pictures/USB.png
** Is this a real language?
*** 
Believe it or not, everything we need is here
* Code is data
** Church encodings
Church encodings are representations of /data/ as /functions/ that use the data
** Natural numbers
*** 
Numbers are functions of the form $\lambda s. \lambda z. ??$
*** 
$0 := \lambda s. \lambda z. z$

$S := \lambda n. \lambda s. \lambda z. s (n\, s\, z)$
** How are *these* numbers?
$1 := S(0) = \lambda s. \lambda z. s (0\, s\, z) = \lambda s. \lambda z. s\, z$

$2 := S(1) = \lambda s. \lambda z. s (1\, s\, z) = \lambda s. \lambda z. s (s\,z)$
** The meaning of a natural number
   The number =N= represents doing /something/ =N= times
   \\
   \\
   $\text{double} = 2$
** Definite iteration
   Natural numbers encapsulate the act of definite iteration
   
** Arithmetic
#+BEGIN_EXPORT latex
\begin{align*}
m + n &:= m(S)(n) \\
1 + 1 &= 1(S)(1) = S(1) = 2 \\
2 + 2 &= 2(S)(2) = S(S(2)) = 4 \\
3 + 5 &= 3(S)(5) = S(S(S(5))) = 8
\end{align*}

\begin{align*}
 m*n &:= m(n(S))(0) \\
 1*1 &= 1(1(S))(0) \\
     &= 1(S)(0) = S(0) = 1 \\
 2*2 &= 2(2(S))(0) \\
     &= 2(S)(2(S)(0)) = 2(S)(2) = 4  
\end{align*}

#+END_EXPORT
** Booleans
We represent true and false as /functions/
#+BEGIN_EXPORT latex

\begin{align*}
\text{true} &:= \lambda t.\, \lambda f.\, t \\
\text{false} &:= \lambda t.\, \lambda f.\, f
\end{align*}

#+END_EXPORT

** The bool is the choice
if-expression:
#+BEGIN_EXPORT latex

$$\text{if} := \lambda b.\, \lambda t.\, \lambda f.\, b\,t\,f$$ 

#+END_EXPORT
examples:
#+BEGIN_EXPORT latex

\begin{align*}
\text{if}(\text{true})(x)(y) &= \text{true}(x)(y) = x \\
\text{if}(\text{false})(x)(y) &= \text{false}(x)(y) = y
\end{align*}

#+END_EXPORT
the choice is built into the booleans themselves

** Pairs
Pair types (two things joined together):
#+BEGIN_EXPORT latex
\begin{align*}
  \text{pair} &:= \lambda l. \, \lambda r.\, \lambda p.\, p(l)(r) \\
  \text{fst} &:= \lambda p. p (\lambda l.\, \lambda r.\, l) \\
  \text{snd} &:= \lambda p. p (\lambda l.\, \lambda r.\, r)
\end{align*}
#+END_EXPORT

We could also have written:
#+BEGIN_EXPORT latex
\begin{align*}
  \text{fst} &:= \lambda p. p(\text{true}) \\
  \text{snd} &:= \lambda p. p(\text{false})
\end{align*}
#+END_EXPORT
** Lists
A list is empty, or an element followed by a list

#+BEGIN_EXPORT latex
\begin{align*}
  \text{nil} &:= \lambda c. \lambda n. n \\
  \text{cons}(x,xs) &:= \lambda c. \lambda n. c\, x (xs\, c\, n)
\end{align*}
#+END_EXPORT
** Understanding reduce/fold
List with three elements
#+BEGIN_EXPORT latex
\begin{align*}
  ourList :=& cons(1,cons(2,cons(3,nil))) \\
  ourList(+,0) =& 1 + cons(2,cons(3,nil))(+,0) \\
               =& 1 + 2 + cons(3,nil)(+,0) \\
               =& 1 + 2 + 3 + nil(+,0) \\
               =& 1 + 2 + 3 + 0 \\
\end{align*}
#+END_EXPORT

#+BEGIN_SRC js :exports code
  [1,2,3].reduce(function (x,y) {return x + y},0)
#+END_SRC
** A lesson from Church encodings
  Thinking inductively $\Rightarrow$ modular code
* Control flow
** What about control flow?
*** 
   We've /almost/ shown Turing completeness
** Recursion
#+BEGIN_EXPORT latex
 $ Y := \lambda f. (\lambda x. f(x\,x)) (\lambda x. f (x\,x))$

#+END_EXPORT
** A simple proof it works
#+BEGIN_EXPORT latex
\begin{align*}
Y(g) &= (\lambda x.\, g(x x))(\lambda x.\, g(x x)) \\
     &= g((\lambda x.\, g(x x))(\lambda x.\, g(x x))) \\
     &= g(Y(g)) 
\end{align*}
#+END_EXPORT
** Sequencing code
#+BEGIN_EXPORT latex
\begin{displaymath}
  l_1;l_2 \Rightarrow (\lambda x. l_2) l_1
\end{displaymath}
#+END_EXPORT
** Variable binding*
#+BEGIN_EXPORT latex
\begin{displaymath}
  \text{let}\, x\,=\,v\, \text{in}\, M \Rightarrow (\lambda x. M) v 
\end{displaymath}
#+END_EXPORT
** Global variable binding*
Easiest with variable hoisting
#+BEGIN_EXPORT latex
\begin{displaymath}
  \text{var}\,x\,=\,v;M \Rightarrow (\lambda x. M) v
\end{displaymath}
#+END_EXPORT
** Compilation as language design
You can experiment with features via compilation between languages
* Lessons learned
** $\lambda$ : a common language
*** 
The $\lambda$ calculus can be found inside many languages

** $\lambda$ : a PL toolkit
***                                                               :B_columns:
    :PROPERTIES:
    :BEAMER_env: columns
    :END:
****                                                                  :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.4
     :END:
   The common language of PL researchers
****                                                                  :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.4
     :END:

file:~/Pictures/tapl.jpg
** $\lambda$ : a way to understand computation
   Formal mathematical models let us get at the heart of computation
** Questions
*** 
#+BEGIN_EXPORT latex
{\Huge Any Questions?}
#+END_EXPORT
** Bonus slides
*** 
#+BEGIN_EXPORT latex
{\Huge GUESS WE HAD MORE TIME!}
#+END_EXPORT
** What about /mutable variables/?
***                                                               :B_columns:
    :PROPERTIES:
    :BEAMER_env: columns
    :END:
****                                                                  :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.3
     :END:
Mutable variables can be /simulated/
****                                                                  :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.45
     :END:
***** The secret origin of monads
file:~/Pictures/moggi.png 
** Closures + state
***                                                               :B_columns:
    :PROPERTIES:
    :BEAMER_env: columns
    :END:
****                                                                  :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.45
     :END:
$\lambda$ + state = everything
****                                                                  :BMCOL:
     :PROPERTIES:
     :BEAMER_col: 0.45
     :END:
file:~/Pictures/LOL.jpg
